# 1-animation
- domain_lora_scale: 1.0
  adapter_lora_path: "models/Motion_Module/v3_sd15_adapter.ckpt"
  dreambooth_path:   ""

  inference_config: "configs/inference/inference-v3.yaml"
  motion_module:    "models/Motion_Module/v3_sd15_mm.ckpt"

  controlnet_config: "configs/inference/sparsectrl/latent_condition.yaml"
  controlnet_path:   "models/SparseCtrl/v3_sd15_sparsectrl_rgb.ckpt"
  # controlnet_config: ""
  # controlnet_path: ""

  H: 512
  W: 512
  seed: [123,234]
  steps: 25
  guidance_scale: 8.5

  controlnet_image_indexs: [0, 1, 2]
  controlnet_images:
    # - "__assets__/demos/image/dog/frame_0.png"
    # - "__assets__/demos/image/dog/frame_1.png"
    # - "__assets__/demos/image/dog/frame_2.png"
    - "__assets__/demos/image/coffee_1.png"
    - "__assets__/demos/image/coffee_2.png"
    - "__assets__/demos/image/coffee_3.png"
  # controlnet_image_indexs: ""
  # controlnet_images: ""

  prompt:
    - "a robot arm is pushing a white mug towards the coffee machine"
    # - "a robot arm is pushing a white mug towards the coffee machine"
    # - "a pharaoh hound running over a grassy field"
    # - "a dog is running"
  n_prompt:
    - "worst quality, low quality, letterboxed"

